#!/bin/bash
# Bash config for build commands

# compile generator
alias build='
if [ ! -d ./build ]; then
    mkdir ./build
fi
echo compiling generator sources &&\
$(
    cd ./build &&
    g++ -c ../source/*.cpp &&
    g++ *.o --static -o generator
)
echo "compiled binary:" &&\
ls -algh --color ./build/generator &&\
bincopy'

# test generator
alias test='sudo cp ./html/style.css / && ./build/generator file=html/format/format.md'

# build container image
alias container-build='echo building container && sudo docker build -t mdgen .'

# start container
alias start='echo running container && sudo docker run -p 8080:80 --restart unless-stopped --name md-generator mdgen'

# stop container
alias stop='sudo docker kill $(sudo docker ps -q -l)'

# get running container id
alias container-id='sudo docker ps -q -l'

# start shell inside running container
alias shell='sudo docker exec -it $(container-id) bash'

# build everything and start container
alias compose='build && container-build && start'

# copy current webfiles into running container
alias webcopy='sudo docker cp ./html/ $(container-id):/var/www && sudo docker exec -it $(container-id) chown -R www-data:www-data /var/www/html'

# copy generator binary into running container
alias bincopy='sudo docker cp ./build/generator $(container-id):/usr/bin'
