IMAGE_NAME='mdgen'
CONTAINER_NAME='mdgen-test'
VOLUME_NAME='mdgen-test'
SITE_NAME='MDGen Test'
DOC_ROOT='/usr/local/apache2/htdocs'
RO_PORT='8080'
RW_PORT='8081'
RO_HOST='localhost'
RW_HOST='localhost'
THEME='default'
VERBOSE='0'