#!/bin/bash
# Bash config for build commands
# usage: '. bashrc' or 'source bashrc'

source ../mdgen/bashrc

CONTAINER_NAME='rezepte'
VOLUME_NAME='rezepte' 
RO_PORT='8082'
RW_PORT='8083'

alias remove='echo removing container $CONTAINER_NAME && sudo docker rm -f $(container-id -a)'

alias run='echo running container $CONTAINER_NAME &&\
sudo docker run --detach -p $RO_PORT:80 -p $RW_PORT:81 --volume $VOLUME_NAME:$DOC_ROOT/pages --name $CONTAINER_NAME --restart unless-stopped $IMAGE_NAME'

alias volume-create='sudo docker volume create $VOLUME_NAME && copy-in && volume-chmod'
alias volume-remove='sudo docker volume rm $VOLUME_NAME > /dev/null && echo removed volume $VOLUME_NAME'
alias volume-chmod='container-running && sudo docker exec $(container-id) /opt/set-dir-visible.sh $DOC_ROOT/pages'

alias copy-in='
sudo docker run -v $VOLUME_NAME:/data --name volume_helper busybox true &&
sudo docker cp ./pages/. volume_helper:/data &&
echo copied files to volume $VOLUME_NAME
sudo docker rm volume_helper
'

alias copy-out='
sudo docker run -v $VOLUME_NAME:/data --name volume_helper busybox true &&
sudo docker cp volume_helper:/data/. ./pages &&
echo copied files to volume $VOLUME_NAME
sudo docker rm volume_helper > /dev/null
'