IMAGE_NAME='mdgen'
CONTAINER_NAME='rezepte'
VOLUME_NAME='rezepte'
SITE_NAME='Kochbuch'
DOC_ROOT='/usr/local/apache2/htdocs'
RO_PORT='8082'
RW_PORT='8083'
RO_HOST='rezepte.fvsion.de'
RW_HOST='rezepte-edit.fvsion.de'
